import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components2/Navbar";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
